2024-12-16 20:53:19,842 INFO    MainThread:62776 [wandb_setup.py:_flush():68] Current SDK version is 0.19.1
2024-12-16 20:53:19,842 INFO    MainThread:62776 [wandb_setup.py:_flush():68] Configure stats pid to 62776
2024-12-16 20:53:19,842 INFO    MainThread:62776 [wandb_setup.py:_flush():68] Loading settings from /home/zifan/.config/wandb/settings
2024-12-16 20:53:19,842 INFO    MainThread:62776 [wandb_setup.py:_flush():68] Loading settings from /home/zifan/drqv2_pytorch/outputs/2024-12-16/20-53-19/wandb/settings
2024-12-16 20:53:19,842 INFO    MainThread:62776 [wandb_setup.py:_flush():68] Loading settings from environment variables
2024-12-16 20:53:19,842 INFO    MainThread:62776 [wandb_init.py:_log_setup():528] Logging user logs to ./results/wandb/run-20241216_205319-6f3wlfw2/logs/debug.log
2024-12-16 20:53:19,842 INFO    MainThread:62776 [wandb_init.py:_log_setup():529] Logging internal logs to ./results/wandb/run-20241216_205319-6f3wlfw2/logs/debug-internal.log
2024-12-16 20:53:19,842 INFO    MainThread:62776 [wandb_init.py:init():644] calling init triggers
2024-12-16 20:53:19,842 INFO    MainThread:62776 [wandb_init.py:init():650] wandb.init called with sweep_config: {}
config: {'_metadata': ContainerMetadata(ref_type=typing.Any, object_type=None, optional=True, key=None, flags={'struct': True}, flags_root=False, resolver_cache=defaultdict(<class 'dict'>, {'now': {('%Y-%m-%d',): '2024-12-16', ('%H-%M-%S',): '20-53-19'}}), key_type=typing.Any, element_type=typing.Any), '_parent': None, '_flags_cache': {'struct': True}, '_content': {'frame_stack': 3, 'action_repeat': 2, 'discount': 0.99, 'num_seed_frames': 4000, 'eval_every_frames': 10000, 'num_eval_episodes': 10, 'save_snapshot': False, 'replay_buffer_size': 1000000, 'replay_buffer_num_workers': 4, 'nstep': 3, 'batch_size': 256, 'seed': 1, 'device': 'cuda:1', 'save_video': True, 'save_train_video': False, 'use_tb': True, 'experiment': 'exp', 'use_wandb': True, 'lr': 0.0001, 'feature_dim': 50, 'num_train_frames': 3100000, 'stddev_schedule': 'linear(1.0,0.1,500000)', 'task_name': 'quadruped_walk'}}
2024-12-16 20:53:19,842 INFO    MainThread:62776 [wandb_init.py:init():680] starting backend
2024-12-16 20:53:19,842 INFO    MainThread:62776 [wandb_init.py:init():684] sending inform_init request
2024-12-16 20:53:19,857 INFO    MainThread:62776 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-12-16 20:53:19,858 INFO    MainThread:62776 [wandb_init.py:init():697] backend started and connected
2024-12-16 20:53:19,858 ERROR   MainThread:62776 [wandb_init.py:init():1308] error in wandb.init()
Traceback (most recent call last):
  File "/home/zifan/miniconda3/envs/drqv2/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1298, in init
    return wi.init()
  File "/home/zifan/miniconda3/envs/drqv2/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 700, in init
    run = Run(
  File "/home/zifan/miniconda3/envs/drqv2/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 577, in __init__
    self._init(
  File "/home/zifan/miniconda3/envs/drqv2/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 682, in _init
    self._config._update(config, ignore_locked=True)
  File "/home/zifan/miniconda3/envs/drqv2/lib/python3.8/site-packages/wandb/sdk/wandb_config.py", line 180, in _update
    sanitized = self._sanitize_dict(
  File "/home/zifan/miniconda3/envs/drqv2/lib/python3.8/site-packages/wandb/sdk/wandb_config.py", line 267, in _sanitize_dict
    k, v = self._sanitize(k, v, allow_val_change)
  File "/home/zifan/miniconda3/envs/drqv2/lib/python3.8/site-packages/wandb/sdk/wandb_config.py", line 285, in _sanitize
    val = json_friendly_val(val)
  File "/home/zifan/miniconda3/envs/drqv2/lib/python3.8/site-packages/wandb/util.py", line 646, in json_friendly_val
    converted = asdict(val)
  File "/home/zifan/miniconda3/envs/drqv2/lib/python3.8/dataclasses.py", line 1073, in asdict
    return _asdict_inner(obj, dict_factory)
  File "/home/zifan/miniconda3/envs/drqv2/lib/python3.8/dataclasses.py", line 1080, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
  File "/home/zifan/miniconda3/envs/drqv2/lib/python3.8/dataclasses.py", line 1110, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
TypeError: first argument must be callable or None
2024-12-16 20:53:19,963 WARNING MsgRouterThr:62776 [router.py:message_loop():75] message_loop has been closed
